
import os
import shutil
from pygoogle_image import image as pi


# Specify the desired folder path
folder_path = 'C:\\downloadb2bimages\\itemimages\\image1'
os.makedirs(folder_path, exist_ok=True)

descriptions =  [

"MOOOTIFUL Gouda Cheese Loaf 2.5kg",
"MOOOTIFUL Mini Butter Tubs 200x7g",
"MOOOTIFUL Cream Cheese 2.5kg",
"MOOOTIFUL Cheddar Loaves 2.5kg rdw",
"MOOOTIFUL Mozzarella Loaves 2.5kg rdw",
"MOOOTIFUL Unsalted Butter 500g",
"MR SAUCE Basting Sauce 5l",
"MR SAUCE Beef Stock 1kg",
"MR SAUCE Cajun Spice 1kg",
"MR SAUCE Cayenne Pepper 1kg",
"MR SAUCE Chicken Spice 1kg",
"MR SAUCE Chicken Stock 1kg",
"MR SAUCE Curry Calcutta 1kg",
"MR SAUCE Cumin Ground 1kg",
"MR SAUCE Oreganum Rubbed 1kg",
"MR SAUCE Parsley Whole 1kg",
"MR SAUCE Paprika Ground 1kg",
"MR SAUCE Lemon & Herb Sauce 5l",
"MR SAUCE Turmeric Ground 1kg",
"MR SAUCE Pedros Lemon & Herb Spice 1kg",
"MR SAUCE Sweet Chilli Sauce 5l",
"MR SAUCE Chicken Spice Tub 600g",
"MR SAUCE Chips Spice Tub 700g",
"MR SAUCE Fish Seasoning Tub 500g",
"MR SAUCE Curry Hot Tub 500g",
"MR SAUCE Paprika GR Tub 500g",
"MR SAUCE Steak & Chops Tub 600g",
"MR SAUCE Barbeque Jumbo 200ml",
"MR SAUCE Steak & Chops Jumbo 200ml",
"MR SAUCE Chicken Jumbo 200ml",
"MR SAUCE BLACK Pepper Coarse Jumbo 125g",
"MR SAUCE Parsley Jumbo 35g",
"MR SAUCE Mixed Herbs Jumbo 60g",
"MR SAUCE Garlic Flakes Jumbo 130g",
"MR SAUCE Fish Seasoning Jumbo 120g",
"MRS BALLS Chutney 470g",
"MW Packaging White Vinegar 5l",
"SPICE Brine Mix 12kg",
"NANDO'S Peri-Peri Sauce Medium 250g",
"NANDO'S Peri-Peri Sauce Hot 250g",
"NANDOS Peri-Peri Sauce Mild 250ml",
"DI NAPOLI Cannellini White Bean 400g",
"DI NAPOLI Borlotti Bean 400g",
"DI NAPOLI Butter Bean 400g",
"DI NAPOLI Passata Glass Bottle 690g",
"NATURES GARDEN Peas 1kg",
"NATURES GARDEN Sweetcorn 1kg",
"NESTLE Milo 500g",
"NESCAFE Ricoffy 1.5kg",
"NESCAFE Ricoffy 750g",
"NESCAFE Coffee 200g",
"NESCAFE Classic Strong 200g",
"NESCAFE Coffee Sticks Decaf 200's 200x1.8g",
"NESCAFE Coffee Decaf 200g",
"NESTLE Condensed Milk 385g",
"NESTLE Cocoa 250g",
"NESTLE Caramel Treat Dessert 360g",
"NESTLE Nespray Powdered Milk 400g",
"NESTLE Hot Chocolate 500g",
"NESTLE Hot Chocolate 1kg",
"NESTLE Dessert Cream 290g",
"Meat Bags 20cmx30cm",
"Carrier Bag Midi 1's",
"GLAD Baking Paper 5m x 300mm",
"Assorted Microfibre Cloth",
"PARACHUTE Coconut Oil 1l",
"Mutton Cloth Rolls 3mtr",
"GLAD Freezer Bags 10's",
"BLITZ Fire Lighters 12's 500g",
"FOIL Catering 440mm x 70m",
"Hardings Methanol Chafing Heating Fuel Tin-GEL 24x230g",
"HOUSEWIVES Cooking Gel 2l",
"HARDINGS Cater Gel 5l",
"Ice Block Bag 1xSTD",
"DISC PADLOCK Stainless Steel 63mm",
"MW PAPER - Tidy Wipe Roll 1.kg",
"ZIPLOC Plastic Storage Bags 15's ",
"Peaceful Sleep Stick Repellant 30g",
"Peaceful Sleep Insect Repellant Cream 100ml",
"Peaceful Sleep Original Aerosol 150g",
"Peaceful Sleep Mats 30's",
"Peaceful Sleep Mosquito Room Spray 300ml",
"Scourer Pot Heavy Duty",
"Serviettes 100's",
"TWINSAVER Facial Tissue 180's",
"TWINSAVER Facial 3 PLY Tissues 120g",
"TWIN SAVER Baking Paper 5mx300mm",
"BABY SOFT Toilet Tissue 2 PLY 18s",
"FOMO Pack Tray 73125",
"FOMO Pack Tray 70250",
"FOMO Pack Tray - 71250",
"Disposable Chopsticks Wrapped 100s",
"NSP BBQ Loin  Ribs 2kg",
"NSP Cubed Bacon 250g",
"NSP Streaky Bacon 250g",
"NSP BBQ Loin Ribs 5kg",
"NSP Back Bacon 1kg",
"NSP Streaky Bacon 1kg",
"NSP Back Bacon 250g",
"NSP Kassler Steak 500g rdw",
"NSP Cooked Marinated Loin Rib 1kg",
"NSP Cooked Marinated Belly Rib 1kg",
"NSP Cheese Griller 1.2kg",
"CISCOS Dried Apricot 1kg",
"CISCO Macadamia Nuts 1kg",
"NUTS Walnuts 1kg",
"CISCO Peanuts & Raisins 1kg",
"CISCO Dried Mango 1kg",
"CISCOS Chutney Corn 100g",
"CISCO Dried Cranberries 1kg",
"Cisco's Pecan Pieces 1kg",
"NUTS Almonds Whole 500g",
"NUTS Cashew Nuts Salted 500g",
"NUTS White Pistachio 500g",
"NUTS About Cooking Coconut Oil 1l",
"SIMBA Peanuts & Raisins 450g",
"NUTS Cashew 1kg",
"NUTS Pecans Halves 1kg",
"NUTS Pistachio Roasted Salted 1kg",
"OMO Handwashing Powder  1kg",
"OREO Milk Cookies 119g",
"OROS Orange Squash 2ltr",
"Clear Bags 45X60 (1000)",
"Promo Pack Food Tray 3075",
"Fomo Pack Food Tray 4075",
"Plastic Meat Bag 25X40 (250)",
"Vaccum Bags 150X200 (100)",
"Vaccum Bags 150X250 (100)",
"Vaccum Bags 200x30 (100)",
"Vaccum Bags 250x30 (100)",
"Vaccum Bags 350X550 (100)",
"PARTY MIX Assorted Sweets 300g",
"Panko Bread Crumbs 1kg",
"PARMALAT Plain Medium Fat Cream Cheese 230g",
"PARMALAT Gouda 230g",
"PARMALAT Plain Double Cream Yoghurt 1kg",
"PARMALAT Double Cream 6x100g",
"PARMALAT Cheddar 230g",
"PARMALAT Yoghurt Plain 500g",
"PARMALAT Yoghurt Plain 1ltr",
"PARMALAT Yoghurt Apricot 1l",
"PARMALAT Yoghurt Strawberry Medium Fat 1ltr",
"PARMALAT Yoghurt Fruit Cocktail 1l",
"PARMALAT Fruit Custard 1kg",
"PARMALAT Milk Pods 50x20ml",
"",
"Peppadew Whole 60% A10",
"PEPPADEW Sweet Piquante Peppers Mild 280g",
"PEPPADEW Piquante Peppers Whole Mild 400g",
"PERE FROMAGE Grated Pecorino 1kg",
"PERE FROMAGE Halloumi 3kg",
"PERE FROMAGE Grated Parmeson 1kg",
"PERE FROMAGE  Pecorino Heads rdw",
"DOOM Multi Insect Spray 300ml",
"DOOM Mosquito Coils 125g",
"DOOM Lavender 300ml",
"POLAR Ice Cream Vanilla 5l",
"POLAR Strawberry Ice Cream 5l",
"POLAR Ice Cream Chocolate 5l",
"POT OGOLD Black Beans in Brine 400g",
"POT O GOLD Fig Jam 720g",
"PRESIDENT Creamy Blue 100g",
"PRESIDENT Plain Feta 400g",
"PRESIDENT Camembert 125g",
"PRESIDENT Feta Plain 200g",
"PRESIDENT Plain Cream Cheese 230g",
"MR SAUCE Barbeque Sauce 5ltr",
"Dextrose Monohydrate Powder 1kg",
"YUM YUM Peanut Butter Smooth 400g",
"AIRWICK Air Freshener Aqua Marine 280ml",
"AIRWICK Air Freshener Cotton Breeze 280ml",
"HINDS Steak & Chops Refill 80g",
"HINDS BBQ Spice Refill 65g",
"HINDS Tumeric Refill 60g",
"HINDS Cayenne Pepper Refill 55g",
"HINDS Parsley Refill 12g",
"HINDS Mixed Herbs Refill 18g",
"COBRA Active Tile Cleaner 1.5ltr",
"TWINSAVER Kitchen Paper Towel 2's",
"PACIFIC WEST Tempura Prawn 2125 200g",
"PACIFIC WEST Prawns Tempura 1620 1kg",
"Quinoa Red 1kg",
"Quinoa White 1kg",
"RAMA Margarine 500g",
"REGAL Assorted Chocolate  500g",
"RELIANZ Nuts Almonds Flaked 1kg",
"RELIANZ Whole Black Peppercorns 1kg",
"RELIANZ  Cashew Nuts Roasted & Salted 1kg",
"RELIANZ Mixed Roasted Nuts 1kg",
"RHODES Smooth Apricot Jam 900g",
"Rhodes Mixed Fruit Jam 450g",
"RHODES Apricot Halves 410g",
"RHODES Green Beans 410g",
"RHODES Tomato & Onion Mix 410g",
"RHODES Pineapple Crush 410g",
"RHODES Tomato Puree 410g",
"RICE Tastic Natures Brown 1kg",
"RICE Tastic Natures Brown Rice 1kg",
"RICE Basmati 2kg",
"RICE Tastic Brown Rice 2kg",
"RICE Tastic Cakes 115g",
"RICE Tastic Parboiled 10kg",
"RICE Tastic Basmati Rice 1kg",
"RICE Sushi 1kg",
"RICH'S Versatie Long Life Cream 1ltr",
"ROBERTSONS Ground Cumin 100ml",
"ROBERTSONS Chicken Spice 1kg",
"ROBERTSONS Savoury Rice Spice 1kg",
"ROBERTSONS Blue Food Colouring 40ml",
"ROBERTSONS Cinnamon 42g",
"ROBERTSONS Ground Ginger 100ml",
"ROBERTSONS White Pepper Fine 100g",
"ROBERTSONS Black Pepper Fine 100g",
"ROBERTSONS Tumeric Spice 100ml",
"ROBERTSONS Ground Coriander 100g",
"ROBERTSONS Parsley 100ml",
"ROBERTSONS Rozemary 100ml",
"ROBERTSONS Sweet Basil 100ml",
"ROBERTSON Thyme Spice 17g",
"ROBERTSONS Baking Powder 1kg",
"ROBERTSON Whole Cinnamon Sticks 24g",
"ROBERTSON Cinnamon 100g",
"ROBERTSON Essence Vanilla Flavour 500ml",
"ROBERTSONS  Ground Ginger refill 50g",
"ROBERTSONS Envelope Spice  Chicken 7g",
"ROBERTSONS Envelope Spice BBQ 7g",
"ROBERTSONS Barbecue Spice 60g",
"ROBERTSONS Chicken Spice 85g",
"ROBERTSONS Bicarbonate Of Soda 14g",
"ROBERTSONS Tumeric Spice Refill 57g",
"ROBERTSONS Rajah Curry Powder 200g",
"ROBERTSONS Paprika Refill 50g",
"ROBERTSONS Mixed Spice 100ml",
"ROBERTSONS Ground Nutmeg 100ml",
"ROBERTSONS  Whole Cloves 26g",
"ROBERTSONS Thyme DRY 100ml",
"ROSES Passion Fruit Cordial 750ml",
"ROSES Lime Cordial 750ml",
"ROULOU Traditional Feta 700g",
"ROULOU Cape Herbs Feta 700g",
"ROULOU Traditional Feta 370g",
"ROYAL Baking Powder 500g",
"SAFARI Peanuts Roasted & Salted 450g",
"SAFARI Fruit Salad 250g",
"SAFARI Sultanas 250g",
"SAFARI  Seedless Raisins  500g",
"SAFARI Dried Prunes 500g",
"SAFFRON Rice Basmati 5kg",
"SALT Flamingo Coarse 1kg",
"SALT Table Fine 1kg",
"SAN REMO Gluten Free Spaghetti 350g",
"SAN REMO Gluten Free Penne 350g",
"SAN REMO Gluten Free Fettuccine 350g",
"SAN REMO Gluten Free Lasagne 200g",
"SANFORD Ling Fillets Ungraded 13kg",
"SANTA BIANCA Black Pitted Olives 340g",
"Mediterranea Garlic, Oil & Chilli Pepper 980g",
"GOLDCREST Sundried Tomato Pesto 140g",
"Schweppes Dry Lemon 24x200ml",
"APPLETISER 24x330ml",
"RED Grapetiser 24x330ml",
"SPRITE 24x300ml",
"Schweppes Soda Water  24x200ml",
"SCHWEPPES Lemonade 24x200ml",
"SCHWEPPES Ginger Ale 24x200ml",
"COKE Slim Regular 24x300ml",
"COKE Slim Zero Sugar 24x300ml",
"FANTA Orange 24x300ml",
"Schweppes Indian Tonic Water 24x200ml",
"STONEY Ginger Beer 24x300ml",
"SEA HARVEST Prawn Meat Peeled n Deveined 800g",
"SECHABA Mabele 5kg",
"SEEDS Gemelli Linseed 1kg",
"SEED Liberty Pumpkin Seeds 1kg",
"LIBERTY Sesame Seeds 1kg",
"LIBERTY Sunflower Seeds 1kg",
"SEED Sunflower 500g",
"SENN Cooked Beef 250g",
"SENN Cooked Ham 250g",
"SENN  Back Bacon 250g",
"SENN Streaky Bacon 250g",
"SENN Mixed Polony 250g",
"SENN Salami Smoked Sliced 250g",
"SENN Pastrami 250g",
"SENN Smoked Ham 250g",
"SENN Chilli Russians 1kg",
"SENN Back Bacon 1kg",
"SENN Streaky Bacon 1kg",
"SENN Cooked Ham 125g",
"SENN Mixed Polony 125g",
"SENN Patsrami 125g",
"SENN Smoked Salami 125g",
"SENN Smoked Ham 125g",
"SENN Sandwich Ham 125g",
"SERENA Whole Peeled Tomatoes 400g ",
"SERENA Italian Whole Peeled Tomatoes 2.65kg",
"SERENA Couscous Original 500g",
"SERENA Original Couscous  1kg",
"SERENA Lasagne Sheets 500g",
"SERENA Red Wine Vinegar 500ml",
"SERENA Risotto Arborio Rice 1kg",
"SHERIDANS Gelatine 125g",
"SIMBA Creamy Cheddar Chips 48x36g",
"SIMBA Mexican Chilli Chips 36g",
"MARVELLO  Multipurpose 50% Fat Spread",
"MEADOWLAND Long Life Cream 1ltr",
"SNACKTIME Assorted Crackers 400g",
"SNOW WHITE Self Raising Flour 2.5kg",
"SNOW WHITE White Bread Flour 12.5kg",
"SNOW WHITE Cake White Flour 12.5kg",
"SOAP Lifebuoy Assorted 175g",
"SOURCE Water 24x500ml",
"SOUTH SPICE Fish Spice 1kg",
"",
"SPICE Poppadums Glutenfree 80g",
"SPICE - Braai Wors 1kg",
"SPICE - Dad's Choice Boerewors 500g",
"SPICE - MOM's CHOICE CHARGRILL BURGER RP 1kg",
"SPICE - Chicken Burger 1kg",
"SPICE - Chilli Bites kg",
"SPICE - Dry Wors 1kg",
"SPICE - Pastrami Seasoning 1kg",
"SPICE - Pork Sausage 1kg",
"SPICE - Pork Sausage 1.2kg",
"STAFFORDS Coconut Milk 400ml",
"STAFFORDS Capers in Vinegar 130g",
"STAFFORDS Black Pitted Olives 340g",
"STAFFORDS Green Pitted Olives 340g",
"STAFFORDS Green Stuffed Olives 340g",
"STAFFORDS Whole Maraschino Cherries Without Stem 400g",
"STAFFORDS Mint Sauce 135g",
"ST DALFOUR Blackcurrent Fruit Jam 284g",
"SUGAR Blue Crystal Golden Brown 5kg",
"SUGAR Blue Crystal Brown 2.5kg",
"SUGAR Blue Crystal White 2.5kg",
"PURE Brown Sugar 5kg",
"SUGAR Blue Crystal White Sugar 12.5kg",
"SUGAR Pure White 12.5kg",
"SUGAR Blue Crystal Golden Brown 8kg",
"SUGAR Blue Crystal White 5kg",
"SUNFOIL Cooking Oil Sunflower 20lt",
"SUNLIGHT B-Soap 175g",
"SUNLIGHT 2in1 Handwashing Powder 1kg",
"SUNLIGHT Washing Powder 2kg",
"SUNLIGHT Dishwashing Liquid 750ml",
"SUNSTAR Cooking Oil 2l",
"Five Rose Rooibos Cater Pack 200x2.0g",
"Five Roses  Cater Pack 200x2.0g",
"1883 Macadamia Syrup 1ltr",
"1883 Watermelon Syrup 1ltr",
"KOO Baked Beans 410g",
"WIM Chilli Mayo 5ltr",
"FBG Five Roses Tagged Teabags 100's",
"FBG Tikka Sauce 5ltr",
"FBG Sweet Chilli Sauce 5ltr",
"FBG Lemon & Herb 5ltr",
"FBG Honey & Mustard Dressing 5ltr",
"FBG TruFruit Apple Juice 5ltr",
"CHEF Easy Cook Non Stick Spray 500ml",
"TEAM Sliced Gherkins 1kg",
"Slo-Jo Berrynade 1ltr",
"Slo-Jo Passionade 1Ltr",
"Slo-Jo Mangoade 1ltr",
"FBG Trufruit Pure Mango 5ltr",
"FBG Toothpicks Wrapped 1000's",
"Refresher Towels Interim 100's",
"VALDIGRANO Tagliatelle 500g",
"CHEF Lemon Juice 2ltr",
"AIR Freshener Bio Nu-Eco 300ml",
"DISHWASHER Powder BIO Nu-Eco 5ltr",
"CHEF Chopped Tomatoes 400g",
"Mop Caps White 100's",
"CATERCORP Peri Peri Saucelicious 5ltr",
"TEA Rooibos Tea Bags 80's",
"SERVIETTES 1 Ply 3000's",
"BRAVO CHEF Whole Peeled Tomatoes 410g",
"TEEKANE Darjeeling Tea 20's",
"TEEKANE Moroccan Mint Tea 20's",
"TETLEY Green Tea 20's",
"THOKOMAN Smooth Peanut Butter 2.75kg",
"LIBERTY Coconut Milk 400ml",
"KIMWIPE Econo Jumbo Roll 1 Ply",
"TOILET PAPER 1 Ply 48's",
"BABY SOFT Toilet Paper 2Ply 9's",
"",
"3 STRMS Hotsmoked Kippers Skinpacked 10x +-200g rdw",
"TSWANA Pride Chicken Portions IQF 2kg ",
"TSWANA Pride Chicken Nuggets 1kg",
"",
"TWININGS Four Red Fruits Tea 50g",
"DILMAH Natural Rooibos Tea (50x2g) Enveloped",
"DILMAH RANGE Black Tea Decaffienated Ceylon (25x2g) Enveloped",
"DILMAH Black Tea Lemon & Lime (25x2g) Enveloped",
"DILMAH Black Tea English Breakfast (25x2g) Enveloped",
"DILMAH Black Tea Earl Grey (25x2g) Enveloped  ",
"DILMAH Black Tea English Afternoon (25x2g) Enveloped ",
"DILMAH Black Tea Darjeeling (25x2g) Enveloped ",
"DILMAH Black Tea Blackcurrent (25x2g) Enveloped ",
"DILMAH Black Tea Lemon (25x2g) Enveloped ",
"DILMAH Peppermint (25x1.5g) Enveloped",
"DILMAH Camomile (25x1.5g) Enveloped",
"DILMAH Rosehip & Hibiscus (25x1.5g) Enveloped",
"DILMAH Green Tea Moroccan Mint (25x1.5g) Enveloped",
"DILMAH Black Tea Ginger & Honey (25x2g) Enveloped ",
"DILMAH Premium Ceylon (100x2.4g) Enveloped",
"ICE Cubes  Bag 1xSTD",
"WILLOW CREEK Squeeze Me Extra Virgin Olive Oil 1lt",
"WILLOW CREEK Balsamic Vinegar 500ml",
"WILLOW CREEK Balsamic Glaze 250ml",
"WILLOW CREEK Balsamic Vinegar 1lt ",
"WELLINGTON Red Wine Vinegar 500ml",
"WELLINGTON Brown Balsamic Vinegar 500ml ",
"WELLINGTONS White Wine Vinegar 500ml",
"WELLINGTON Chutney Mild 450g",
"WELLINGTON Chutney Hot 450g",
"WELLINGTON'S Sweet Chilli Sauce 375ml",
"WELLINGTONS Apple Cider Vinegar 500ml",
"WIENER MISCHUN - Filter Coffee 250g ",
"WINGSON Spirit Vinegar White 375ml",
"WOODYS Back Bacon 6x1kg",
"WOODYS Streaky Bacon 6x1kg",
"WOODYS Back Bacon 200g",
"WOODYS Streaky Bacon 200g",
"Wooden Knives 100's",
"XMAS CRACKERS  EACH",
"ZEENAT'S Cocktail - Beef Mince Samoosa 25g 12's",
"ZEENAT'S Cocktail - Potato & Peas Samoosa 25g 12's",
"ZEENAT'S Cocktail - Chicken Samoosa 25g 12's",
"Lamb Leg Deboned & Netted VP - per kg",



]

# Specify the desired size for the new image
desired_size = (300, 300)  # Adjust the size as needed

for description in descriptions:
    # Change the current working directory to the desired folder
    os.chdir(folder_path)

    # Download images without specifying output_directory
    pi.download(description, limit=10)
    # Change back to the original working directory
    os.chdir("..")
    print(description, 'downloaded successfully')
