import os
import shutil
from pygoogle_image import image as pi


# Specify the desired folder path
folder_path = 'C:\\downloadb2bimages\\itemimages\\image4'
os.makedirs(folder_path, exist_ok=True)

descriptions =  [


"OLD EL PASO Seasoning Mix Spice 25g",
"OLE Tomato Sauce 340g",
"OLE Tomato Pulp 340g ",
"OLE Tomato Sauce & Olives 340g",
"OLE Bolognese Tomato Sauce 340g ",
"OLE Tomato Sauce & Fine Herbs 340g",
"OLITALIA Balsamic Glaze 500ml",
"OLITALIA Glaze with Aceto Balsamico Di Modena Classic 250ml",
"omaru",
"French Fries 10mm 1kg Omega BEL",
"OMEGA French Fries 18x1kg",
"OMEGA French Fries 20x1kg ",
"French Fries 10mm 10x1kg Omega BEL",
"OMO Hand Wash Washing Powder 3kg",
"OMO Bleach Ass 750ml",
"OMO Auto Liquid 3l",
"OMO Regular Washing Powder 600g",
"OMO  Handwash 6x6x600g (Shrink)",
"Sunlight 2in1 600g",
"OMO Auto Washing Powder 9kg",
"OMO Hand Washing Powder 9kg",
"Opstal Sixpence Sauvignon BlancSemillion 2015 750ml (6)",
"Opstal Sixpence Cab SauvignonMerlot 2014 750ml (6)",
"Opstal Chenin Blanc 750ml (6)",
"Opstal Estate Cabernet SauvCinsault 2017 750ml (6)",
"Poly Box Small (480x320x125)",
"Poly Box Big (800x400x180)",
"PANCHO'S Wraps Plain 25cm 6's",
"PANCHO'S Wraps Wholewheat 25cm 6's",
"PANKO Bread Crumbs 200g",
"PANKO Bread Crumbs 1kg",
"Custard Clover 6x1lt",
"PARMALAT Everfresh UHT Milk FC 6x1lt ",
"PARMALAT Everfresh UHT Milk 2% Low fat 6x1l ",
"PARMALAT Dairy Snack Yoghurt Pineapple 48x48x100g  ",
"PARMALAT Dairy Snack Yoghurt Banana  48x48x100g  ",
"PARMALAT Dairy Snack Yoghurt Strawberry 48x48x100g  ",
"PARMALAT Dairy Snack Yoghurt Plain 48x48x100g  ",
"PARMALAT Dairy Snack Yoghurt Tropical 48x48x100g  ",
"PAW PATROL Creamy Dip 35g",
"PEREIRA Portuguese Sardines 600g",
"Halloumi Cheese rdw",
"Halloumi PERE FROMAGE 3kg",
"PIES Homemade Venison 650g",
"",
"",
"PIPING Pizza Cones Frozen Empty Large 49s 2kg",
"PIPING Pizza Cones Frozen Empty Mini 49s 1.94kg",
"PIPING Pizza Cones Frozen Empty Large Baked 8's",
"PIPING Pizza Cones Frozen Empty Mini Baked 8's",
"PIE IN THE SKY Roasted Onion Herb Boiled Bagel 4sx110g ",
"PIE IN THE SKY Cocktail Pasteis de Nata (Custard Filling) 72x40g",
"PIE IN THE SKY Traditional Pasteis de Nata (Custard Filling) 72x65g",
"PIE IN THE SKY Bagels Plain 6x110g",
"PIE IN THE SKY Bagels Roasted Onion & Herb 6x110g",
"PIE IN THE SKY Roasted Onion Herb Boiled Bagel 20x4s 80x110g  ",
"PIE IN THE SKY Cocktail Pasteis de Nata (Custard Filling) 6x40g",
"PIE IN THE SKY Traditional Pasteis de Nata (Custard Filling) 6x65g",
"PJ Masks Marshamallow Pops 45g",
"Plastic Bag",
"Paprika",
"POLAR Premier Vanilla Ice Cream 2lt",
"POLAR Guilt Free Ice Cream Vanilla 6x1l",
"POLAR NJA Classic Range Rum & Raisin Ice cream 2lt",
"POLAR NJA Classic Range Mint Choc Chip Ice Cream 2lt",
"POLAR NJA Classic Range Choc Nut Sundae Ice cream 2lt",
"POLAR NJA Frozen Dessert Choc Vanilla 2lt",
"POLAR NJA Frozen Choc Mint 2lt",
"POLAR Premium Full Cream Fresh Strawberry Ice Cream 2lt",
"POLAR Premium FCream Toffee Nut Ice Cream 2lt",
"POLAR Premium  Chocolate Ice Cream 2lt",
"POLAR Premium Full Cream Toasted Almond Ice Cream 2lt",
"POLAR Premium Full Cream Blueberry Cheesecake Ice Cream 2lt",
"POLAR Premium Full Cream Rum & Raisin Ice Cream 2lt",
"POLAR Premium Fresh Strawberry Ice Cream 2lt",
"POLAR Guilt Free Ice Cream Mint Choc Chip 6x1l",
"POLAR NJA Classic Vanilla Fudge 5lt",
"POLAR NJA Classic Range Double Caramel Ice Cream 5lt",
"POLAR NJA Classic Range Mint Choc Chip Ice Cream 5lt",
"POLAR NJA Vanilla Fudge 5lt",
"POLAR NJA Cheeky Choc Mint 5lt",
"POLAR NJA Choc Vanilla 5lt",
"POLAR NJA Black Forest 5lt",
"POLAR Guilt Free Ice Cream Espresso Choc Chip 6x1l",
"POLAR Cups Choc Vanilla 12x500g",
"POLAR Nja Chocolate 5l",
"POLAR KOSMOSNIKS Bonoffee 5lt",
"POLAR KOSMOSNIKS Bubblegum 5lt",
"POLAR KOSMOSNIKS Mango Split 5lt",
"POLAR KOSMOSNIKS Mixed Berry 5lt",
"POLAR KOSMOSNIKS Strawberry 5lt",
"POLAR KOSMOSNIKS Bananaberry 5lt",
"POLAR Fruit Licks Mix OrangeRaspberryPineapple 30x70ml",
"POLAR Premium Blueberry Cheesecake Ice Cream 5l",
"POLAR NJA Very Vanilla Ice Cream 5l",
"POLAR Premium Velvet Vanilla Ice Cream 5l",
"POLAR CUP Banana and Strawberry 500ml",
"POLAR KOSMOSNIKS Vanilla 5l",
"POLAR Cannolis 24s",
"POLAR Icup Toasted Almond 24x125ml",
"POLAR Milky 30s",
"POLAR Fruit Licks Mix OrangeRaspberryPineapple 70ml",
"POLAR Berry Blaze 30x70ml",
"Polar NJA Strawberry Ice Cream 2lt",
"POLAR Float Mix StrawberryOrangePassionfruit 20x70ml",
"POLAR Cannolis 6x36s",
"POLAR Sandwich Vanilla & Strawberry 80ml",
"POLAR Milky Pie 25x70ml",
"POLAR Milky Pie 70ml",
"POLAR Granadilla Sherbet 20s",
"POLAR Icup Mango 125ml",
"POLAR Icup Pist n Nuts 125ml",
"POLAR Icup Toasted Almond 125ml",
"POLAR Float Mix StrawberryOrangePassionfruit 70ml",
"POLAR Maxi Ruby 100g",
"POLAR Maxi Ruby Chocolate 6x100ml",
"POLAR Maxi Chocolate Therapy 6x100ml",
"POLAR Maxi White Almond 16x90ml",
"POLAR Maxi Chocolate Therapy 100ml",
"POLAR Maxi White Almond 90ml",
"POLAR Icup Almond 125ml",
"POLAR Icup Mango 125ml",
"POLAR Icup Tin Roof 125ml",
"POLAR Maxi 6 Pack Chocolate Therapy 10x6x100ml",
"POLAR Maxi 6 Pack Ruby Chocolate 10x6x100ml",
"POLAR Coconut Bar 15x85ml",
"POLAR Kisses 24s",
"POLAR Guilt Free Ice Cream Mint Choc Chip 1l",
"POLAR Guilt Free Ice Cream Espresso Choc Chip 1l",
"POLAR Guilt Free Ice Cream Vanilla 1l",
"POLAR Sandwich Vanilla & Strawberry 24x80ml",
"POLAR Sandwich Vanilla 1s",
"POLAR Coconut Bar 85ml",
"POLAR Kisses 6x24s",
"POLAR Icup Burfee 24x125ml",
"POLAR Icup Mango 24x125ml",
"POLAR Icup Tin Roof 24x125ml",
"POLAR Icup Pist n Nuts 24x125ml",
"Polar Stick Woza 16's",
"Polar Stick Rasberry Pop 30's",
"Polar Stick Tropaz 30's",
"Polar Cup Bananaberry ( Straw & Banana)12x500g",
"Polar Stick Litchilik 30's",
"Polar Stick Banana Split 30's",
"Polar Cups Chocolate 24x125ml",
"Polar Cups Strawberry 24x125ml",
"POLAR Stick Rave Strawberry Swirl 20's",
"",
"POLENGHI Lemondor Unsweetened Lime Juice 125ml",
"POLANA Pasta Fusilli 500g",
"POLANA Spaghetti 500g",
"POLANA Spaghetti 24x250g",
"POLANA Spaghetti 250g",
"POLANA Instant Noodles Ass 70g",
"POMIDORO Whole Peeled Tomatoes 2.5kg    ",
"Potato Starch 1kg",
"POT Ó GOLD Baby Apples with Stem In Syrup 425g ",
"POWERADE Ass  4x6x500ml",
"Sandwich Ham Diced 1kg PS",
"PEARL RIVER BRIDGE Oyster Sauce 2.35kg",
"PRIMA Luncheon Roll 280g",
"Pronto Fresco Pizza Sauce 4.1kg",
"STEAMED Fruit Pudding 400g",
"PACIFIC WEST Crumbed Prawns Cutlets 1620 6x1kg",
"PACIFIC WEST Salt & Pepper Squid Chunks 3x1kg",
"PACIFIC WEST Crumbed Calamari Rings Reformed 5x1kg",
"PACIFIC WEST Tempura Squid Rings 5x1kg",
"PACIFIC WEST Chilli Squid 3x1kg",
"PACIFIC WEST Salt & Pepper Squid Bites 5x1kg",
"PACIFIC WEST Salt & Pepper Squid Chunks 12x360g",
"PACIFIC WEST Southern Style Prawns 6x300g",
"PACIFIC WEST Panko Prawns 2630 16x200g",
"PACIFIC WEST Seafood Snack Pack 16x200g",
"PACIFIC WEST Panko Prawns 1620 1kg",
"PACIFIC WEST Salt & Pepper Squid 1kg",
"PACIFIC WEST Prawn Portions 300g",
"PACIFIC WEST Salt & Pepper Squid Chunks 360g",
"PACIFIC WEST Chilli Squid 1kg",
"PACIFIC WEST Panko Prawns Crumbed 1620 200g",
"PACIFIC WEST Crumbed Prawn Cutlets 2630 500g",
"PACIFIC WEST Seafood Snackpack 200g",
"PACIFIC WEST Tempura Squid Rings 1kg",
"PACIFIC WEST Crmbd Formed Squid & fish Ring 1kg",
"RADOX Body Wash Feel Energized 250ml",
"RAMA Marg 250g",
"RAMA Original Tub 60% 1kg",
"RED SQUARE Blue Ice Blueberry 275ml",
"RED SQUARE Red Ice Cranberry 275ml",
"RED SQUARE Blue Ice Blueberry 6x275ml",
"RED SQUARE Red Ice Cranberry 6x275ml",
"RED SQUARE Purple Ice LBerry 275ml",
"RED SQUARE Purple Ice LBerry 6x275ml",
"RED SQUARE Pink Ice Grapefruit 275ml",
"RED SQUARE Pink Ice Grapefruit 6x275ml",
"REESE'S Peanut Butter Topping 198g",
"RELIANZ Corn Flour 500g",
"REMY MARTIN Cognac Fine Champagne V.S.O.P 750ml",
"RHODES Baked Beans A10",
"RHODES Juice MangoOrange 24x200ml",
"RHODES Tomato Puree 410g",
"RHODES Chakalaka Mild n Spicy 400g",
"RHODES Chhakalaka Hot N Spicy 12x400g",
"RHODES Tomato & Onion Mix A10              ",
"RHODES Gherkins Dill 3.06kg",
"RHODES  Juice Orange 100% 6x1l",
"RHODES Juice Cranberry 100% 6x1l",
"Rhodes Juice Apple 100% 6x1",
"RHODES Juice Orange 100% 1l",
"RHODES Cranberry Juice 1Litre",
"RHODES Butter Beans In Tomato Sauce 12x400g",
"RHODES Pineapple Pieces A10",
"RHODES Pineapple Rings 440g",
"RICE KING Long Grain 2kg    ",
"RICH Mini Pain Au Chocolat 70x75g (02349)",
"RICH Sandwich Baguettes 50x100g",
"RICH Speedibake Croissant 70x80g (04700) ",
"RICHS Donut Holes 20x11g",
"RICH On Top Whip 6x850ml",
"RICH German Pretzels 60x80g",
"RICH FTO Cheese Twists 100g 6's",
"RICH FTO Croissants 10x40g ",
"RICH Mini Tart Base 240x20g (02443)",
"RICH Sweet Premium Banana Choc Nut Muffins 12x120g ",
"RICH IW Mix Muffins 55g ",
"RICH Small Tart Base 200x45g",
"RICH FTO Cheese Twists 100g 8x600g",
"RICH FTO Croissants 40g 13x400g",
"RICH Mini Custard Puffs 40g 13x360g ",
"RICH FTO Mini Danish Selection 120x40gx45gx50g (16455)",
"RICH Ciabatta Roll 20x110g (16576) ",
"RICH Sweet Premium Banana Choc Nut Muffins 24x120g (16732)",
"RICH Bagels Plain 50x100g",
"RICH Bagels Multigrain 50x100g",
"RICH Blueberry Muffin Batter 6x1.36kg",
"RICH Pretzels German 6x80g",
"RICH Eclairs Raspberry 12x73g",
"RICH Rustic Baguette Plain 20x270g",
"RICH Mini Pain Au Chocolat 12x30g",
"RICH Custard Sweet Puffs 50x100g (29394)",
"RICH FTO Croissants 8x80g",
"RICH Mini Custard Puffs 9x40g",
"RICH Muffin Batter Selection 1.36kg ",
"RICH Ciabatta Roll 4s",
"RICH Bagels Plain 5s PP",
"RICH Bagels Multigrain 6x100g PP",
"RICH Pizza Bases Thin Large 300mm 5x250g",
"RICH Pizza Bases Thin Med 230mm 5x170g",
"RICH Pizza Bases Thin Small 180mm 10x100g",
"RICH Bagels Plain 6x100g",
"RICH Bagels Multigrain 5x100g PP",
"RISTORIS Tomatoes Semi Dried Tin 6x750g",
"RISTORIS Semi-Dried Red Tomatoes 750g",
"RISTORIS Tomatoes Dried 6x800g",
"RISTORIS Dried Tomatoes 800g",
"RISTORIS Mushrooms Sauteed Tin 6x800g",
"RISTORIS Sauteed Mushroom Mix 800g",
"RISTORIS Robo Long Stem Artichokes 6x750g",
"RISTORIS Roman Style Artichokes 750g",
"RISTORIS Artichoke Hearts 6x2.4kg",
"RISTORIS Artichoke Hearts In Brine 2.4kg",
"RISTORIS Caramalized Sliced Onions 800g",
"RISTORIS Onions Sliced Caramelized Tin 6x800g",
"RISTORIS Eggplant Sliced Grilled Tin 6x750g",
"RISTORIS Grilled Eggplant Slices 750g",
"RISTORIS Peppers Grilled Tin 6x800g",
"RISTORIS Grilled Peppers 800g",
"RISTORIS Zucchine Grilled Slices Tin 6x780g",
"RISTORIS Grilled Zucchini Slices 780g",
"RISTORIS Olives Stuffed 6x780g",
"RISTORIS Stuffed Green Olives 780g",
"RISTORIS Giant Olives Cocktail Tin 6x780g",
"RISTORIS Giant Cocktail Olives 780g",
"RISTORIS Artichoke Quarters 6x2.5kg",
"MC Country Crop 24x250g",
"ROBERTSONS Black Pepper 100g",
"ROBERTSONS BBQ Spice 100g",
"ROBERTSONS Spice Rajah Medium Curry Powder 100g",
"ROBERTSONS Cloves 100ml",
"ROBERTSONS Nutmeg 100ml",
"ROBERTSONS Rajah Hot 800g",
"ROBERTSONS Black Pepper Envelopes 40x7g",
"ROBERTSONS Rajah Curry Powder All in One Env 40x7g",
"ROBERTSONS Whole Cloves 26g",
"ROBERTSONS Spice Chicken Envelopes 4x40x7g",
"ROBERTSONS Chicken Env 40x7g",
"ROBERTSONS White Pepper Env 40x7g",
"ROBERTSONS Lemon Pepper 80g",
"ROBERTSONS Spice Meat Teneriser 80g",
"ROBERTSONS Spice For Fish 80g",
"ROBERTSONS Chip n Potato Seasoning Spice Pouch 1kg ",
"ROBERSTONS Chicken Spice Pouch 1kg ",
"ROBERSTONS Rajah Medium Curry Powder Pouch 800g",
"ROBERTSONS Smoked Paprika 600g",
"ROSA Sardines 125g",
"ROSES Kola Tonic FL Cordial 750ml      ",
"ROYAL Rice 25kg",
"ROYCO Sauce Black Pepper 38g ",
"RICH Muffin Baked Cappuccino Choc Chip IW 48x55g",
"RICH Muffin Baked Double Choc IW 48x55g (3153)",
"RICH Muffins Baked Blueberry IW 48x55g",
"RICH Muffins Baked Bran & Raisin IW 48x55g",
"RUGANI Abc Juice 330ml",
"RWANDA ISIMBIS Coffee Beans 1kg",
"Braai Wors Chakalaka (S5) 10x500g TASTY",
"Braai Wors Egte (S5) 10x500g TASTY",
"Braai Wors Egte (S5) 500g TASTY",
"Braai Wors Chakalaka (S80) 10kg (80x125g) TASTY",
"Braai Wors Egte (S80) 10kg (80x125g) TASTY",
"SACLA Pesto Black Summer Truffle 90g",
"SACLA Pasta Sauce Whole Cherry Tomato with Basil 350g",
"SACLA Pasta Sauce Whole Cherry Tomato with Olives 350g",
"SACLA Pesto Chilli 190g",
"SACLA Pesto Sundried Tomato 190g",
"SACLA Pesto Classic Basil 190g",
"SACLA Pesto Rocket & Basil 190g",
"SACLA Oven-Baked Tomatoes & Chilli 285g",
"SACLA Oven-Roasted Tomatoes with Olives 285g",
"SACLA Artichokes Marinated 285g",
"SALDANHA Pilchards Saldanha Tomato Talls 400g",
"SALDANHA Pilchards Saldanha Tomato Talls 12x400g ",
"SALDANHA Pilchards In Tomato 24x115g",
"Salt Course 25kg    ",
"Salt Course 50kg",
"Pink Salt N Pepper Twin pack",
"Jalapeno Poppers 4's",
"SAUCEMANS Worcester Sauce 5l",
"SAUCEMAN'S BBQ Sauce 5l",
"COCA COLA 2ltr",
"Lemon Twist 2ltr",
"Schweppes Granadilla Twist 2ltr",
"Fanta Grape 2ltr",
"Fanta Orange 2ltr",
"Sprite 2ltr",
"COCA COLA Zero 24x330ml ",
"SPARLETTA Sparberry 4x6x300ml ",
"SPARLETTA Pine Nut 4x6x300ml ",
"Fanta Pineapple 24x300ml ",
"Coca Cola 200ml",
"ENERGADE Sport Jellies Sweets 24x125g",
"Energade Sport Jellies 125g",
"SPARLETTA Pine Nut 300ml",
"OCEAN BOMB Bubble Milk Tea 315ml",
"OCEAN BOMB Bubble Milk Tea Original 315ml",
"COCA COLA Cherry Vanilla 355ml",
"DR PEPPER Vanilla 355ml",
"FANTA Peach 355ml",
"FANTA Strawberry 355ml",
"COCA COLA Dry Lemon 24x200ml",
"FANTA Apple 2l",
"COCA COLA Cherry 355ml",
"SPARLETTA Cream Soda 4x6x300ml ",
"COCA COLA Vanilla 355ml ",
"COCA COLA Lemonade 24x200ml",
"COCA COLA 300ml ",
"COCA COLA 6x300ml",
"Lemon Twist 24x300ml",
"Sprite LemonLime Flavoured Drink 300ml",
"SPARLETTA Creme Soda 300ml ",
"SPARLETTA Sparberry 300ml",
"FANTA Pineapple 300ml",
"SPRITE 300ML",
"SPARLETTA Granadilla Twist 6x2l",
"Fanta Red Apple 2l",
"SCHWEPPES Dry Lemon 24x200ml",
"Viking Pilchards large 12x1kg",
"SEA HARVEST Prawn Meat 2040 800g   ",
"SEA HARVEST Prawn Meat 4060 800g ",
"SEA HARVEST Crabstick 1kg",
"SEA HARVEST Black Tiger Prawn 1315 800g",
"Seed Mix 1kg ",
"Liberty Sugar Tubes White Selati 1000 x5g",
"SERENA Canneloni 250g",
"SERENA Red Kidney Beans in Brine 400g",
"SERENA Artichoke Hearts in Brine 390g",
"SERENA Lasagne Sheets 250g",
"SERENA Lasagne Spinach 250g",
"SERENA Risotto Arborio Rice 1kg",
"SERENA Potato Gnocchi 500g",
"SERENA Whole Cherry Tomatoes 400g",
"SERENA Wholewheat Cous Cous 500g",
"SERENA Balsamic Vinegar 250ml",
"SERENA Tagliatelle 500g",
"SERENA Capelli Dángelo 500g",
"SERENA Spaghettini 500g",
"SERENA Linguine 500g",
"SERENA Penne Rigate 500g",
"SERENA Fusilli 500g",
"SERENA Pipe Rigate 500g",
"SERENA Farfalle (Bowties) 500g",
"SERENA Tri Color 500g",
"SERENA Basil Pesto 140g",
"SGAMBARO Pasta Spaghetti 500g",
"SGAMBARO Pasta Tortiglioni 500g",
"SGAMBARO Pasta Penne Rigate 91 500g",
"SGAMBARO Pasta Fusili 500g",
"Sea Shells 140g",
"SHAKE ME Smoked BBQ Spice 158g",
"SHAKE ME Chicken BBQ 165g",
"SIMBA Chips Mexican Chilli 120g",
"SIMBA Chips Original Chutney 25g",
"SIMBA Chips Mexican Chilli 24x125g",
"SIMBA Potato Chips Creamy Cheddar 24x120g",
"SIMBA Potato Chips Smoked Beef 24x120g",
"SIX GUN Drywors Safari 1kg",
"Saltletts Mini Brezel 12x150g",
"Cheese Grillers rdw",
"SNOWFLAKE Muffin Easy Mix Cappuccino Flavour 1kg ",
"SNOWFLAKE Muffin Easy Mix Vanilla Flavour 1kg ",
"SONADOR Belgium Message Slab 30g",
"SOUP OF THE DAY Fresh Vegetable Soup 500g",
"SOUP OF THE DAY Fresh Vegetable Soup 6x500g",
"SOUP OF THE DAY Leek & Potato Soup 6x500g",
"SOUP OF THE DAY Sundried Tomato & Basil Soup 500g",
"SOUP OF THE DAY Sundried Tomato & Basil Soup 6x500g",
"Chickentizer Crispy Strips 1kg",
"Chicken Kebabs 115g SOV",
"Chicken Kebabs 35x115g 4kg SOV",
"Chicken Breast Fillet 100p 4x2.5kg  SOV (Shop)",
"Caterchicken Soup Pack 1kg SOV",
"Chicken Mixed Portions 4kg Seshebo SOV",
"Chicken Mixed Portions 5kg SOV",
"Chicken Mixed Portions 1.5kg SOV",
"Chicken Livers 1kg SOV",
"Chicken Mixed Portions 3x4kg Seshebo SOV",
"Chicken Liver 10x1kg SOV ",
"Chicken Chip Fries Orginal 6x1kg TIZER",
"Chicken'tizer Breast Fillet Hot&Spicy 2kg",
"Chicken Breast Fillet 100% 2.5kg  SOV",
"Chicken Country Range Strips Crumbed SOV 750g",
"Chicken Country Range Burger Patties Crumbed SOV 750g",
"Chicken Country Range Burgers Crumbed SOV 750g",
"Chicken Country Range Nuggets Crumbed SOV 750g",
"Chicken'tizer Wings Original 1.5kg",
"Chicken'tizer Thighs Original 1.5kg",
"Chicken'tizer Drumsticks Orig 95g-125g 1.5kg",
"Chicken Mixed Portions 2kg SOV",
"Chicken'tizer Cheesy Crumbed Schnitzel 1kg",
"Chicken'tizer Cheesy Crumbed Burger 975g",
"Chicken'tizer Burgers Chilli Cheese  65g 975g",
"Chicken'tizer Cheese Chilli Bites 20g 1kg",
"Chicken'tizer Cheese Chilli Strips 50g 1kg",
"Chicken'Tizers Chicken Chip Fries Battered 1kg",
"Chicken'tizer Burger crumbed  5.85kg (2919)",
"Chicken'tizer Crispy Strips 6x1kg (3830)",
"Chicken'tizer SStyle Buffalo Wing HotSpicy 1kg",
"Chicken'tizer SStyle Crumbed Schnitzel 125g 6kg",
"Chicken'tizer SStyle Crumbed Schnitzel 125g 1kg",
"Chicken'tizer SStyle Buffalo Wings Orig 35g-55g 6kg",
"Chicken'tizer Sstyle Buffalo Wings 1kg ",
"Chicken'tizer SStyle Buffalo Wing HotSpicy 35g-55g 6kg",
"Chicken'tizer SStyle Pops 6x1kg",
"Chicken'tizer SStyle Pops 1kg",
"Peppadew Pepper n Garlic Seasoning Spice 138g",
"SPARKLING ICE Water Black Raspberry 500ml",
"SPARKLING ICE Water Orange Mango 500ml ",
"SPARKLING ICE Water Kiwi Strawberry 500ml",
"SPARKLING ICE Water Peach Nectarine 503ml",
"SPARKLING ICE Water Cherry Limeade 500ml",
"SPARKLING ICE Water Black Cherry 503ml",
"SPICEY CORNER Leaf Masala 100g",
"SPICEY CORNER 11 in 1 Masala 100g",
"SPICEY CORNER Durban Masala 100g",
"SPICEY CORNER Kokni Masala 100g",
"SPICEY CORNER Fish Masala 100g",
"SPICEY CORNER Seafood Masala 100g",
"SPICEY CORNER Chicken Spice 100g",
"SPICEY CORNER Chicken Braai 100g",
"SPICEY CORNER Barishap 100g",
"SPICEY CORNER TurmericBorrie 100g",
"SPICEY CORNER Brown Breyani Masala 100g",
"SPICEY CORNER Bistro 100g",
"SPF Pineapple Rings 6x825g",
"Bacon Catering 1kg VP SPMM",
"Bacon Diced 1kg VP SPMM",
"Bacon Streaky 1kg SPMM",
"SPICE & SCALE Pepper White Ground 1kg",
"SPICE & SCALE Rosemary Rubbed 1kg",
"SPICE & SCALE Bay Leaves Whole  1kg",
"SPICE & SCALE World Spirit White Vinegar 5l ",
"SPICE & SCALE BBQ Seasoning 1kg",
"SPICE & SCALE BBQ Special Chilli Bite  1kg",
"SPICE & SCALE World Ginger Ground 1kg",
"SPICE & SCALE Coriander Ground 1kg",
"SPUR Creamy Mushroom Sauce 200ml",
"SPUR Cheddamelt Sauce 200g",
"SPUR Seasoning Classic Blintong 100g",
"SPUR Seasoning Steakhouse 100g",
"SPUR Seasoning Smokey Bbq 100g",
"SPUR Hickory Basting 500ml ",
"SPUR Southern Style BBQ Sauce 500ml",
"SPUR Hickory Maple Bbq Sauce 500ml",
"SPUR Peri-Peri Sauce Creamy Garlic 500ml",
"SPUR Peri-Peri Sauce Smokey 500ml",
"SPUR Salad Dressing 500ml",
"SPUR Salad Dressing 1l",
"SPUR Durky Sauce 500ml",
"SPUR BBQ Sauce 500ml",
"SPUR Sweet Chilli Dressing 500ml",
"SPUR Peri Peri Sauce 500ml",
"SPUR Salad Dressing 300ml",
"SPUR Steak Sauce 500ml",
"SPUR Seasoning Texas Steak 100g",
"SPUR Monkey Gland Sauce 200ml",
"Chickentizer burgers 1kg ",
"Olives Black Pitted 1kg",
"Olives Black Pitted 500g",
"Pickled Curry Fish (+-500g) rdw",
"Basil Pesto (+-500g) rdw",
"Calamari Heads Skin-on rdw",
"Calamari Tubes RDM",
"CG Passionate Lemon 24por",
"MOOOTIFUL White Cheddar Loaves RDW 8x +-2.5kg",
"Crayfish Whole COOKED 10kg",
"MC Shoestring 7mm 1kg ",
"MC Signature Rustic Cut Chips 2.5kg",
"Hake H&G no size",
"Ice Cream Magnum Ass 20's",
"Kingklip H&G 0-1000 rdw",
"Kingklip H&G 2000-3000 rdw",
"Margarine S S D 30x500g (blue)",
"Margarine S S D 48x125g",
"Margarine Wooden Spoon 30x500",
"Oil Sunflower 2L each",
"Samoosas Beef Ckt  STD  100s (Local)",
"Samoosas Chicken & Veg  Ckt 100s (Local)",
"Samoosas Veg. ckt 100s (Local)",
"Samoosas Beef Large 40s",
"Soles Dressed 180210 pcs",
"Soles Dressed 330370 pcs",
"Soles Dressed 430500 pcs",
"Soles Dressed 500600 pcs",
"Soles WR 300450 Rdw",
"Springroll Chicken & Veggie Ckt 100s (Local)",
"Squid Patagonica PP +-200g (PKT)",
"Tabasco Green 60ml",
"Tomatoes Sundried in Oil 2.5kg MEDI DELI",
"Springroll Beef Ckt 100s (Local)",
"Springroll Veg Ckt 100s (Local)",
"Springroll Veg 70s (Local)",
"Ice Cream Cornetto 24x120ml",
"Pickled Curry Fish 5L",
"Crayfish Tails RAW 4.54kg",
"Pizza Bases 4's (22S)",
"Pizza Regina 20`s",
"Pizza Namibian 16s",
"Mussel Meat 500g (Local)",
"Crayfish Tails 1kg Cater Fish",
"Crayfish Raw 2.5kg Cater Fish",
"Herring Bismarck 5kg",
"Herring Rollmops 5kg",
"Kingklip Fillets rdw",
"Mussels Half Shell 500g",
"Prawn Meat 40-60 500g",
"Pizza Hawaii 20s",
"Crab claws 500g",
"Edam Cheese Grated 500g",
"Garlic Spread 450g",
"Gherkins Green 500g rdw",
"Garlic Crushed 500g",
"Ribbon fish rdw",
"MC Veg Carrot Rounds 1kg",
"MC Veg Cauliflower 1kg",
"MC Veg Corn Cut 1kg",
"MC Veg Peas 1kg",
"MC Veg Spinach 1kg",
"MC Veg Sweet Potato 1kg",
"MC Veg Pumpkin 1kg",
"MC Veg Mix Veg 1kg",
"MC Veg Butternut 1kg",
"MC Veg CC Three Way Mix 1kg",
"Waffles Vanilla 5's",
"Crab Sticks 500g",
"Hake Fillets 2-4 PP ",
"Hake Fillets 4-6 pp",
"Angel WR RDW",
"Hake Fillets 6-8 pp",
"Hake Filllets Prime LARGE PP rdw",
"Chicken Breast Smoked Rdw",
"Pita Bread White 6x",
"Monk mixed grading rdw",
"SRD Springroll Pastry Sheets 30's ",
"STA SOFT Baby 2lt",
"STA SOFT Refill Aromatherapy 2l",
"STA SOFT Concentrated Refill Aromatherapy Indulgence 500ml",
"STA SOFT Refill 500g ",
"STA SOFT Concentrated Refill Aromatherapy Passion 500ml",
"STA SOFT Concentrated Refill Aromatherapy Relax 500ml",
"STAR LION Rice Paper 100g",
"STAVROS Whole Calamata Olives In Brine A10 3kg",
"SUNDALE Gouda Loaf rdw",
"SUNLIGHT Liquid Dishwash 400ml ",
"SUNLIGHT Hand Wash Powder Tropical 6x600g",
"SUNLIGHT Handwash Powder 36x500g",
"Fabric Conditioner Gentle Sunlight  2lt",
"SUNLIGHT Laundry Bar 125g",
"Sunshine D Tubs Blue 12x1kg",
"SUNSHINE D 16x125g ",
"SUNSHINE D Lite 40p Spread 1kg",
"SUNWEST Calrose Rice 25kg",
"SUPERIOR Bread Loaf Brown",
"SUPERIOR Bread Loaf White ",
"Sweetie Pies Vanilla 1s",
"SWEETIE PIE Chocolate Balls Raisin 100g",
"SWEETIE PIE Chocolate Balls Peanut 100g",
"SWEETIE PIE Chocolate Balls Shortbread 100g",
"TAFEL Lager 6x330ml ",
"TAFEL Lager Quarts 12x750ml",
"TAFEL Lager 24x500ml - CANS",
"TALL HORSE Wine Chardonnay 750ml",
"TALL HORSE Shiraz 750ml",
"TALL HORSE Sauvignon Blanc 750ml",
"TALL HORSE Wine Merlot 750ml",
"TALL HORSE Cabernet Sauvignon 750ml",
"TALL HORSE  Wine Pinotage 750ml",
"TALL HORSE Wine Chenin Blanc 750ml",
"TASSENBERG Red Wine 750ml",
"BASMATI Rice Trade Routes 2kg  ",
"TASTIC Rice Wholegrain Brown  2kg",
"TASTIC Jasmine Rice 1kg",
"Braai Wors Chakalaka 1kg TASTY",
"Braai Wors Egte 1kg TASTY",
"TAURUS Teak Oil 5l",
"Teak Oil Furn Taurus Red 5ltr",
"Beef Rump Steaks 700g",
"Beef Brisket 600g",
"TEARDROP Glass Bottle Still 24x440ml",
"TEARDROP Glass Bottle Sparkling 24x440ml",
"TEEKANNE Indian Chai Black Tea With Spices 20s",
"TEEKANNE Ginger Turmeric 20s",
"TERRYS Chocolate Orange 157g",
"THIRST BUSTER Powder Drink 60s",
"TOBLERONE 100g",
"TOBLERONE 50g",
"TOBLERONE with Honey n Almond Nougat 35g",
"Tofiluk Caramel Crunch 2's",
"TOFFIFEE 48s",
"Chopped Tomato Bag In Box 10x1kg",
"Tomato Whole Peeled A10",
"Whole Peeled Tomatoes 24x400g ",
"French Fries 7mm 5x2kg Tomex BEL",
"TOP CLASS Soya Mince Beef & Onion 200g ",
"TOP CLASS Spice Mix Original 500g ",
"TRIGZ Crunchy Popped Corn Chips SWEET CHILLI 85g",
"TRIGZ Crunchy Popped Corn Chips WHITE CHEDDAR 85g",
"TRIGZ Jalepeno Flavoured 85g",
"3Streams OAK SMOKED Salmon Shavings 300g",
"3STRMS Oak Smoked Snoek Pate 150g Tub",
"3Streams OAK SMOKED Trout Ribbons 80g",
"3STRMS Norwegian Lumpfish Red Caviar 100g",
"3 STRMS Salmon & Trout Pate 150g",
"3 STRMS Smoked Salmon Offcuts 500g",
"3STRMS Norwegian Lumpfish Black Caviar 100g",
"3STRMS Oak Smoked Butterfish 30x80g ",
"3STRMS Norwegian Lumpfish Black Caviar 12x100g",
"3STRMS Norwegian Lumpfish Red Caviar 12x100g",
"Oak Smoked Salmon & Trout Offcuts 10x500g",
"Oak Smoked Salmon & Trout Pate 24x150g",
"OAK SMOKED SNOEK PATE 24x150g",
"Oak Smoked Snoek Presentation Box 20x500g",
"3STRMS Oak Smoked Trout 10x200g",
"3STRMS Oak Smoked Snoek 1kg ",
"TUTI's Fruit Cakes With Icing Large 600g",
"TUTI's Fruit Cakes With Nuts and Icing Small 330g",
"TWINSAVER Roller Towels 2x150 ",
"TWINSAVER 1PLY Toilet Paper Wrapped 24's",
"TWO OCEANS Caberner Sauvignon Merlot 750ml",
"TWO BEARDS Synergy Blend Coffee Beans 1kg",
"KNORR Tomato Soup 500g",
"KNORR Soup Packet Chicken Noodle 10x50g",
"KNORR Soup Packet Cream of Chicken 50g",
"KNORR Brown Sauce Gravy Base 1kg",
"CARTE D'OR Assorted Fruity Flavoured Jelly 8x500g",
"KNORR Chilli Beef & Veg Soup 10x50g",
"KNORR Peri Peri Marinade 1kg   ",
"KNORR Cream Of Mushroom Soup 10x50g",
"KNORR Mutton & Vegetable Soup 10x50g",
"KNORR Tomato Soup 1.6kg",
"KNORR Jus Sauce 800g",
"KNORR Cream Of Chicken Soup 10x50g",
"KNORR Chakalaka Soup 10x50g",
"KNORR Minestrone Soup 10x50g",
"KNORR Oxtail & Vegetable Soup 10x50g",
"KNORR Thick Vegetable Soup 1.6kg",
"KNORR Minestrone Soup 1.6kg (4)",
"KNORR Brown Onion Soup 10x50g",
"KNORR Beef & Tomato Soup 10x50g",
"VALUPAK Black Refuse Bags on Roll 20's",
"VAN HOLTEN's Kosher Pickle Zesti Garlic Flavour 1's 30g",
"VAN HOLTEN's Tapatio Pickle Tapatio Flavoured 1's 30g",
"VAN HOLTEN's Pickle Hot Mama 1s",
"VASELINE PET Jelly Baby 12x100ml",
"Baby Marrow PP",
"Baby Marrow",
"Corn PP",
"Beans Green",
"Beetroot",
"Broccoli",
"Butternut",
"Cabbage",
"Cabbage Red",
"Carrots",
"Cauliflower PP",
"Cucumber",
"VELHA Snails In Brine 800g  ",
"VELHA Balsamic Vinegar 1lt",
"Cous Cous Velha 250g",
"VERSUS Pengvino White 3l",
"VERSUS Pengvino Red 3l",
"VERSUS Pengvino Sweet Sensation Red 750ml",
"VERSUS Pengvino Sweet Sensation Rose 750ml",
"VERSUS Pengvino Sweet Sensation White 750ml",
"Garlic",
"Ginger",
"Herb Mix PP CORIANDER",
"Lettuce",
"Leeks Bunch",
"Mushrooms White PP",
"Onions Red",
"Onions kg rdw",
"Onions 7kg",
"VOSS Water Sparkling Lemon & Cucumber 375ml",
"Parsley Bunch",
"Patty Pans",
"Peppers Green",
"Peppers Red",
"Peppers Yellow",
"Pineapple ",
"Potatoes Baby ",
"Potatoes 7kg",
"Pumpkin",
"Vrede en Lust White Mischief 2015 750ml (6)",
"VREDE EN LUST Viognier 750ml",
"VREDE EN LUST Ella Syrah 750ml",
"Vrede en Lust Casey's Pinot Noir 2016 750ml (6)",
"Rocket PP",
"Spinach PP",
"Spring Onions PP",
"Squash  Gems ",
"Tomatoes Cocktail PP",
"Tomatoes",
"Tomatoes PP 6's",
"WALKER BAY Variety Spice Pack 6x50g",
"WALKER BAY Mixed Herbs 50g ",
"WALKER BAY Fish Seasoning 120 g ",
"WALKER BAY Mixed Herbs 15g ",
"WALKER BAY Original Braai Salt 400g",
"WALKER BAY Worcester Sauce Braai Salt 400g ",
"WALKER BAY Lemon & Garlic Braai Salt 400g ",
"DILMAH Ice Tea Green Tea Arabian Jasmine 300ml",
"DILMAH Black Tea Lemon n Lime 300ml",
"DILMAH Black Tea Peach 300ml",
"DILMAH Rooibos Mango Gin Tum With Black Pepper 40g",
"DILMAH Green Rooibos Holy Bas Ginger Lem Lemongrass 20s 40g",
"DILMAH Rooibos,Raspberry & Coconut 20's 40g",
"DILMAH Flavoured Ceylon Black Tea Blackcurrant 20's 30g",
"DILMAH Flavoured Ceylon Black Tea Ginger & Honey 20's 30g",
"DILMAH Flavoured Ceylon Black Tea Lemon 20's 30g",
"DILMAH Flavoured Ceylon Black Tea Mango & Strawberry 20's 30g",
"DILMAH Flavoured Ceylon Black Tea Strawberry 20's 40g",
"DILMAH Flavoured Ceylon Black Tea Peach 20's 30g",
"DILMAH Pure Peppermint Leaves 25's 37,5g",
"DILMAH Green Rooibos Lemongrass & Spearmint 20's 40g",
"DILMAH Green Rooibos With Cardamom, Ginger and Orange 20's 40g",
"DILMAH Rooibos Chocolate,Tumeric, Ginger & Almond 20's 40g",
"DILMAH Green Rooibos Coconut & Mango 20's 40g",
"DILMAH Rooibos With Caramel,Ginger & Coconut 20's 40g",
"DILMAH Green Rooibos, Ginger & Peppermint 20's 40g",
"DILMAH Green Rooibos,Lemongrass & Spearmint 20's 40g",
"DILMAH Infusion Tangerine Rose & Grapefruit 20's 40g",
"DILMAH Infusion Bergamot Orange Peppermint & Lemon 20's 40g",
"DILMAH Infusion Rooibos, Chocolate,Tumeric,Ginger & Almond 20's 40g",
"DILMAH Infusion Rooibos, Cinnamon,Tumeric, Ginger & Nutmeg 20's 40g",
"DILMAH Rosehip & Hibiscus 25's 37,5g",
"WILLOW CREEK Squeeze Me Extra Virgin Olive Oil 500ml",
"WILLOW CREEK Squeeze Me Extra Virgin Olive Oil 1lt",
"WILLOW CREEK Balsamic Vinegar 1lt",
"OLIVIA Balsamic Vinegar 5l",
"WILLOW CREEK Estate Blend Extra Virgin Olive Oil Spray 300ml",
"WILLOW CREEK Balsamic Vinegar Oak Matured 250ml",
"WE - Muesli Gluten Free 300g",
"WE - Granola Gluten Free 350g",
"WE - Crushed Onions Sprinkles Seasoned 85g",
"WE - Banana Flour 300g",
"WEBER Chop Spice 200ml",
"WEBER Chicken Spice 200ml",
"WEBER Portuguese Chicken Spice 200ml",
"WEBER Chipotle Lemon Grinder Spice 200ml",
"WEBER Lemon n Herb Chicken Marinade Spice 45g",
"WEBER BBQ Original Sauce 500ml",
"WEBER Sriracha BBQ Sauce 500ml",
"WEDGEWOOD Assorted Nougat 50g",
"WEDGEWOOD Zesty Orange Nougat 40g",
"WEDGEWOOD Nougat Strawberry 140g",
"WEDGEWOOD Salted Caramel 12g",
"WEDGEWOOD Roasted Almond Nougat 40g",
"WELLINGTON'S Tomato Sauce 2lt",
"WERTHERS Original Caramel Chews 45g     ",
"WH Roasted Edamame Beans Large 250g",
"WH Crazy Corn BBQ 50g",
"WH Crazy Corn Cinnamon 50g",
"WH Orange Cream Cookies Sugar Free 75g",
"WH Crazy Corn Lightly Salted 50g",
"WH Crazy Corn Roasted Mealie Kernals Sicy Pepper 50g",
"WH Crazy Corn Roasted Mealie Kernals Spicy Tomato 50g",
"WH Pineapple Cream Cookies Sugar Free 75g",
"WH Edamame Beans White Wasabi 40g",
"WH Edamame Beans Lightly Salted 40g",
"WH Roasted Edamame Beans Small 100g",
"WH Multigrain Cookies Sugar Free 75g",
"WH Crazy Corn Peanut Caramel Popcorn Clusters 100g",
"WH Crazy Corn Almond & Cashews Caramel Popcorn Clusters 100g",
"Wilderer Big Five Giftbox 6x5x40ml",
"Wilderer Blending Box 43% (6x40ml & Glasses)",
"Wilderer Fynbos Gin 500ml",
"WILLARDS Cheese Curls Ass 150g  ",
"WINDHOEK Non Alcaholic NRB 330ml",
"Beer Windhoek Draught Lager 6x440ml",
"Windhoek Lager 6x330ml",
"WINDHOEK Draught Premium 6x500ml",
"YAMAMA Cream Cake Chocolate 50g",
"YAMAMA Cream Cake Chocolate 50g",
"ZAMBEZI Honey Gold 500g",
"Zambuk Cherry Lip 7g 12",
"ZOMBIE Chews Sour Apple 20g",
"Zombie Chews Sour Strawberry 20g",
"MELLO Beef Kiddies Sausage Rolls 10x100g",
"Chicken Livers 500g ",


]

# Specify the desired size for the new image
desired_size = (300, 300)  # Adjust the size as needed

for description in descriptions:
    # Change the current working directory to the desired folder
    os.chdir(folder_path)

    # Download images without specifying output_directory
    pi.download(description, limit=10)
    # Change back to the original working directory
    os.chdir("..")
    print(description, 'downloaded successfully')
